/**
 * safety-resources.ts — Support resources / helplines to surface in a crisis (pure data).
 * Crisis replies are not generated by the LLM — for safety, only fixed wording and verified contacts are used.
 */
import type { Locale } from '@/shared/locale';

export interface SafetyResource {
  name: string;
  phone: string;
  hours: string;
  note: string;
}

const RESOURCES: Record<Locale, SafetyResource[]> = {
  ko: [
    {
      name: '자살예방 상담전화',
      phone: '109',
      hours: '24시간',
      note: '전문 상담원과 즉시 통화할 수 있어요.',
    },
    {
      name: '정신건강 상담전화',
      phone: '1577-0199',
      hours: '24시간',
      note: '가까운 정신건강복지센터로 연결돼요.',
    },
  ],
  en: [
    {
      name: 'Suicide Prevention Hotline (Korea)',
      phone: '109',
      hours: '24h',
      note: 'Talk to a trained counselor right away.',
    },
    {
      name: 'Danuri Helpline (multilingual)',
      phone: '1577-1366',
      hours: '24h',
      note: 'Support in several languages for residents in Korea.',
    },
  ],
};

const CRISIS_REPLY: Record<Locale, string> = {
  ko: '지금 많이 힘드신 것 같아요. 혼자 감당하지 않으셔도 돼요. 자살예방 상담전화 109(24시간)로 전문가와 바로 이야기할 수 있어요.',
  en: "It sounds like you're going through something very hard. You don't have to carry this alone — you can reach a counselor right now at 109 (24h), or the multilingual Danuri Helpline at 1577-1366.",
};

export const safetyResources = (locale: Locale): SafetyResource[] => RESOURCES[locale];

/** Fixed reply sent to the user at the crisis tier. */
export const crisisReply = (locale: Locale): string => CRISIS_REPLY[locale];
