/**
 * safety-resources.ts — Support resources / helplines to surface in a crisis (pure data).
 * Crisis replies are not generated by the LLM — for safety, only fixed wording and verified contacts are used.
 */
export interface SafetyResource {
  name: string;
  phone: string;
  hours: string;
  note: string;
}

const RESOURCES: SafetyResource[] = [
  {
    name: 'Suicide Prevention Hotline (Korea)',
    phone: '109',
    hours: '24h',
    note: 'Talk to a trained counselor right away.',
  },
  {
    name: 'Danuri Helpline (multilingual)',
    phone: '1577-1366',
    hours: '24h',
    note: 'Support in several languages for residents in Korea.',
  },
];

const CRISIS_REPLY =
  "It sounds like you're going through something very hard. You don't have to carry this alone — you can reach a counselor right now at 109 (24h), or the multilingual Danuri Helpline at 1577-1366.";

export const safetyResources = (): SafetyResource[] => RESOURCES;

/** Fixed reply sent to the user at the crisis tier. */
export const crisisReply = (): string => CRISIS_REPLY;
